package com.example.accessingdatamysql.service;

import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.example.accessingdatamysql.model.Course;
import com.example.accessingdatamysql.service.repo.CourseRepository;
import com.example.accessingdatamysql.service.repo.entity.CourseEntity;

@Service    
public class CourseService {

	@Autowired // This means to get the bean called userRepository which is auto-generated by Spring, we will use it to handle the data
	private courseRepository courseRepository;

    public bool checkValid(Course course) {   
        Iterable<CourseEntity> iter = CourseRepository.findAll();
                
        List<Student> ls = new ArrayList<>();    
        iter.forEach(studentEntity -> {
            Student student = new Student();
            student.setId(studentEntity.getId());
            student.setName(studentEntity.getName());
            student.setEmail(studentEntity.getEmail());
            student.setIsActive(1 == studentEntity.getState());
            ls.add(student);
        });    
        return ls;    
    }


    public boolean save(Course course) {
        CourseEntity courseEntity = new CourseEntity();
		courseEntity.setCourseId(course.getCourseId());
		courseEntity.setName(course.getName());
		courseEntity.setCredit(course.getCredit());
		courseEntity.setMaxSeat(course.getMaxSeat());

		if(courseRepository.save(courseEntity))
            return true;

        return false;
    }
}
