package com.example.accessingdatamysql.service;

public package com.example.accessingdatamysql.service;

import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.example.accessingdatamysql.model.Course;
import com.example.accessingdatamysql.service.repo.CourseRepository;
import com.example.accessingdatamysql.service.repo.entity.CourseEntity;

@Service    
public class CourseService {

	@Autowired // This means to get the bean called userRepository which is auto-generated by Spring, we will use it to handle the data
	private courseRepository courseRepository;

    public bool checkValid(Course course) {   
        Iterable<CourseEntity> iter = CourseRepository.queryCourse();
                
        List<Course> ls = new ArrayList<>();    
        iter.forEach(courseEntity -> {
            Course course = new Course();
            course.setId(courseEntity.getId());
            course.setName(courseEntity.getName());
            course.setEmail(courseEntity.getEmail());
            course.setIsActive(1 == courseEntity.getState());
            ls.add(course);
        });    
        return false;    
    }


    public boolean save(Course course) {
        CourseEntity courseEntity = new CourseEntity();
		courseEntity.setCourseId(course.getCourseId());
		courseEntity.setName(course.getName());
		courseEntity.setCredit(course.getCredit());
		courseEntity.setMaxSeat(course.getMaxSeat());

		if(courseRepository.save(courseEntity))
            return true;

        return false;
    }
} {
    
}
